### ISSUE TITLE
AMGx fails to configure with NV HPC_SDK

### ISSUE THREAD

**Issue by thickAsABrick** [Nek5000/nekRS#435]
I am pasting below the CMake error I see when I run nrsconfig:
```
-- Found CUDAToolkit: /opt/nvidia/hpc_sdk/Linux_x86_64/22.3/cuda/11.6/include (found suitable version "11.6.112", minimum required is "10.0") 
This is a MPI build:TRUE
-- Performing Test COMPILER_C_SUPPORTS_MCMODEL
-- Performing Test COMPILER_C_SUPPORTS_MCMODEL - Success
-- Performing Test COMPILER_C_SUPPORTS_MCMODEL_FPIC
-- Performing Test COMPILER_C_SUPPORTS_MCMODEL_FPIC - Success
-- Performing Test COMPILER_Fortran_SUPPORTS_LARGE_DATA_THRES
-- Performing Test COMPILER_Fortran_SUPPORTS_LARGE_DATA_THRES - Success
-- Performing Test COMPILER_Fortran_SUPPORTS_CRAYPTR
-- Performing Test COMPILER_Fortran_SUPPORTS_CRAYPTR - Success
-- Found MPI_UNDERLYING_COMPILER: /opt/cray/pe/gcc/11.2.0/bin/g++

----------------- Summary -----------------
Installation directory: /home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs
C compiler: /opt/cray/pe/craype/2.7.15/bin/cc
C++ compiler: /opt/cray/pe/craype/2.7.15/bin/CC
Fortran compiler: /opt/cray/pe/craype/2.7.15/bin/ftn
Default backend : CUDA
CPU backend compiler: g++ (flags: -O3 -g -march=native -mtune=native)
NVIDIA CUDA backend enabled (flags: -O3 --fmad=true -lineinfo)
GPU aware MPI support enabled
-------------------------------------------
-- Configuring done
CMake Error at CMakeLists.txt:244 (add_library):
  Target "nekrs-lib" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:244 (add_library):
  Target "nekrs-lib" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:244 (add_library):
  Target "nekrs-lib" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:244 (add_library):
  Target "nekrs-lib" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:244 (add_library):
  Target "nekrs-lib" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:244 (add_library):
  Target "nekrs-lib" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:294 (add_executable):
  Target "nekrs-bin" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:294 (add_executable):
  Target "nekrs-bin" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:294 (add_executable):
  Target "nekrs-bin" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:294 (add_executable):
  Target "nekrs-bin" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:294 (add_executable):
  Target "nekrs-bin" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:294 (add_executable):
  Target "nekrs-bin" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:299 (add_executable):
  Target "axhelm-bin" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:299 (add_executable):
  Target "axhelm-bin" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:299 (add_executable):
  Target "axhelm-bin" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:299 (add_executable):
  Target "axhelm-bin" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:299 (add_executable):
  Target "axhelm-bin" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:299 (add_executable):
  Target "axhelm-bin" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:303 (add_executable):
  Target "advsub-bin" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:303 (add_executable):
  Target "advsub-bin" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:303 (add_executable):
  Target "advsub-bin" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:303 (add_executable):
  Target "advsub-bin" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:303 (add_executable):
  Target "advsub-bin" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:303 (add_executable):
  Target "advsub-bin" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:307 (add_executable):
  Target "fdm-bin" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:307 (add_executable):
  Target "fdm-bin" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:307 (add_executable):
  Target "fdm-bin" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:307 (add_executable):
  Target "fdm-bin" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:307 (add_executable):
  Target "fdm-bin" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:307 (add_executable):
  Target "fdm-bin" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at 3rd_party/AMGX/CMakeLists.txt:352 (add_library):
  Target "amgxsh" links to target "CUDA::cublas" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at 3rd_party/AMGX/CMakeLists.txt:352 (add_library):
  Target "amgxsh" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at 3rd_party/AMGX/CMakeLists.txt:352 (add_library):
  Target "amgxsh" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at 3rd_party/AMGX/CMakeLists.txt:349 (add_library):
  Target "amgx" links to target "CUDA::cublas" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at 3rd_party/AMGX/CMakeLists.txt:349 (add_library):
  Target "amgx" links to target "CUDA::cusparse" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at 3rd_party/AMGX/CMakeLists.txt:349 (add_library):
  Target "amgx" links to target "CUDA::cusolver" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
The required libraries are in the LD_LIBRARY_PATH:
```
bramesh@x3107c0s13b0n0:~/RECHERCHE/NekRS/v22.0/nekRS> echo $LD_LIBRARY_PATH
/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/cuda/11.6/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/cuda/11.6/extras/CUPTI/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/cuda/11.6/nvvm/lib64:/opt/cray/pe/gcc/11.2.0/snos/lib64:/opt/cray/pe/papi/6.0.0.14/lib64:/opt/cray/libfabric/1.11.0.4.87/lib64
bramesh@x3107c0s13b0n0:~/RECHERCHE/NekRS/v22.0/nekRS> ls -ltr /opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64
lrwxrwxrwx 1 root root 24 Mar 17 20:30 /opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64 -> targets/x86_64-linux/lib
bramesh@x3107c0s13b0n0:~/RECHERCHE/NekRS/v22.0/nekRS> cd /opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64
bramesh@x3107c0s13b0n0:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64> ls
libcal.so                 libcufft.so.10                libcusolverMg.so.11          libcutensorMg.so.1.5.0
libcublasLt.so            libcufft.so.10.7.1.112        libcusolverMg.so.11.3.3.112  libcutensorMg_static.a
libcublasLt.so.11         libcufft_static.a             libcusolverMp.so             libcutensor.so
libcublasLt.so.11.8.1.74  libcufft_static_nocallback.a  libcusolver.so               libcutensor.so.1
libcublasLt_static.a      libcufftw.so                  libcusolver.so.11            libcutensor.so.1.5.0
libcublas.so              libcufftw.so.10               libcusolver.so.11.3.3.112    libcutensor_static.a
libcublas.so.11           libcufftw.so.10.7.1.112       libcusolver_static.a         liblapack_static.a
libcublas.so.11.8.1.74    libcufftw_static.a            libcusparse.so               libmetis_static.a
libcublas_static.a        libcurand.so                  libcusparse.so.11            libnvblas.so
libcufftMp.so             libcurand.so.10               libcusparse.so.11.7.2.112    libnvblas.so.11
libcufftMp.so.0           libcurand.so.10.2.9.55        libcusparse_static.a         libnvblas.so.11.8.1.74
libcufftMp.so.0.0.2       libcurand_static.a            libcutensorMg.so             stubs
libcufft.so               libcusolverMg.so              libcutensorMg.so.1
```

And, I am using CMake version > 3.18 
```
bramesh@x3107c0s13b0n0:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64> cmake --version
cmake version 3.21.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
bramesh@x3107c0s13b0n0:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64> 
```

I'd appreciate help figuring out why CMake is throwing an error.

**Comment by stgeke** [comment]
Can you please try to build nekRS with AMGx support.

**Comment by thickAsABrick** [comment]
I was also able to build the nekRS executable (without AMGX support). Note the warning below, though:
===
[ 98%] Building CXX object CMakeFiles/nekrs-lib.dir/3rd_party/gslib/ogs/src/oogs.cpp.o
/home/bramesh/RECHERCHE/NekRS/v22.0/nekRS/3rd_party/gslib/ogs/src/ogsSetup.cpp: In function 'ogs_t* ogsSetup(int, long long int*, MPI_Comm&, int, occa::device)':
/home/bramesh/RECHERCHE/NekRS/v22.0/nekRS/3rd_party/gslib/ogs/src/ogsSetup.cpp:237:42: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
  237 |     ogs->localGatherIds = (dlong*) calloc(ogs->Nlocal,sizeof(dlong));
      |                                    ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/cray/pe/gcc/11.2.0/snos/include/g++/bits/std_abs.h:38,
                 from /opt/cray/pe/gcc/11.2.0/snos/include/g++/cmath:47,
                 from /opt/cray/pe/gcc/11.2.0/snos/include/g++/math.h:36,
                 from /home/bramesh/RECHERCHE/NekRS/v22.0/nekRS/3rd_party/gslib/ogs/ogs.hpp:117,
                 from /home/bramesh/RECHERCHE/NekRS/v22.0/nekRS/3rd_party/gslib/ogs/src/ogsSetup.cpp:28:
/usr/include/stdlib.h:426:14: note: in a call to allocation function 'void* calloc(size_t, size_t)' declared here
  426 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^~~~~~
[ 99%] Linking CXX shared library libnekrs.so
[ 99%] Built target nekrs-lib
[ 99%] Building CXX object CMakeFiles/axhelm-bin.dir/src/bench/axHelm/main.cpp.o
[ 99%] Building CXX object CMakeFiles/nekrs-bin.dir/src/main.cpp.o
[ 99%] Building CXX object CMakeFiles/fdm-bin.dir/src/bench/fdm/main.cpp.o
[ 99%] Building CXX object CMakeFiles/advsub-bin.dir/src/bench/advsub/main.cpp.o
[ 99%] Linking CXX executable nekrs
[ 99%] Built target nekrs-bin
[100%] Linking CXX executable nekrs-bench-fdm
[100%] Linking CXX executable nekrs-bench-axhelm
[100%] Linking CXX executable nekrs-bench-advsub
[100%] Built target fdm-bin
[100%] Built target axhelm-bin
[100%] Built target advsub-bin
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Set runtime path of "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/lib/libnekrs.so" to "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/lib"
-- Set runtime path of "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/bin/nekrs" to "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/lib"
-- Set runtime path of "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/bin/nekrs-bench-axhelm" to "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/lib"
-- Set runtime path of "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/bin/nekrs-bench-advsub" to "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/lib"
-- Set runtime path of "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/bin/nekrs-bench-fdm" to "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/lib"
-- Set runtime path of "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/lib/libocca.so" to "/home/bramesh/RECHERCHE/NekRS/v22.0/.local/nekrs/lib"
bramesh@x3007c0s13b1n0:~/RECHERCHE/NekRS/v22.0/nekRS> 
===

**Comment by stgeke** [comment]
Hmm looks like Cuda 11.6 and AMGx is not playing nice together. Unfortunately I cannot test it on our end. We don't have access to a machine with such a new Cuda version.

**Comment by kris-rowe** [comment]
If you pass `-DCMAKE_PREFIX_PATH="${NVHPC_PATH}/math_libs"` to CMake, this seems to do the trick.

**Comment by thickAsABrick** [comment]
---
/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/cuda/11.6/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/cuda/11.6/extras/CUPTI/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/cuda/11.6/nvvm/lib64:/opt/cray/pe/gcc/11.2.0/snos/lib64:/opt/cray/pe/papi/6.0.0.14/lib64:/opt/cray/libfabric/1.11.0.4.87/lib64
---
Since LD_LIBRARY_PATH, as shown above, does not  list /opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs/11.6/lib64 as the first entry, setting -DCMAKE_PREFIX_PATH="/opt/nvidia/hpc_sdk/Linux_x86_64/22.3/math_libs"  solves the nrsconfig problem (as @kris-rowe points out above). However, the subsequent step "cmake --build ./build --target install" fails as:
---
/home/bramesh/RECHERCHE/NekRS/v22.0/nekRS/3rd_party/AMGX/base/include/amgx_cusparse.h:62:10: fatal error: cusparse_v2.h: No such file or directory
   62 | #include <cusparse_v2.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [3rd_party/AMGX/CMakeFiles/amgx_libs.dir/build.make:76: 3rd_party/AMGX/CMakeFiles/amgx_libs.dir/base/src/aggregation/coarseAgenerators/coarse_A_generator.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:567: 3rd_party/AMGX/CMakeFiles/amgx_libs.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
---

**Comment by thickAsABrick** [comment]
@kris-rowe :  do note that a build with AMGX_ENABLED=0 compiles/runs even without passing -DCMAKE_PREFIX_PATH="..." Its the build with AMGX_ENABLED=1, in the nrsconfig script, that is causing problems on Polaris.

**Comment by MalachiTimothyPhillips** [comment]
I've confirmed that `-DCMAKE_PREFIX_PATH="${NVHPC_PATH}/math_libs"` works with `nvhpc/22.3`.

**Comment by stgeke** [comment]
Updating to latest CMake seems to resolve the issue.

**Comment by thickAsABrick** [comment]
I am afraid the problem of not being able to build with AMGX persists even with cmake-3.23.2. It may not be a CMake issue. Perhaps it has more to do with FindCUDAToolKit being unable to find _all_ the CUDA relevant header files in version cudatoolkit-11.6. I do not have access to more than one platform that runs cudatoolkit-11.6. So, for now, this matter remains resolved.

**Comment by thickAsABrick** [comment]
This issue has been resolved.
